# Generated by Django 3.2.7 on 2022-03-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0002_expirydates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpiryDates',
            new_name='ExpiryDate',
        ),
        migrations.RenameModel(
            old_name='SymbolAndTokens',
            new_name='SymbolAndToken',
        ),
    ]
