# Generated by Django 3.2.7 on 2022-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0004_tradebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('order_type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('buy_price', models.CharField(max_length=100)),
                ('half_quantity', models.CharField(max_length=100)),
                ('half_exit_price', models.CharField(max_length=100)),
                ('half_exit_time', models.DateTimeField()),
                ('stoploss', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('sell_price', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('p_n_l', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TradeBook',
        ),
    ]
