# Generated by Django 3.2.7 on 2022-03-15 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0007_activetrade_daywisesummery'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrade',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='buy_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 5, 37, 34, 886033)),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='half_exit_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 5, 37, 34, 886000)),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='half_quantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='order_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='p_n_l',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='sell_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 5, 37, 34, 886027)),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='stoploss',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activetrade',
            name='target',
            field=models.CharField(default='', max_length=100),
        ),
    ]
