# Generated by Django 3.2.7 on 2022-03-15 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0009_auto_20220315_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('symbol', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='00000', max_length=100)),
                ('order_type', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
                ('buy_price', models.CharField(default='', max_length=100)),
                ('half_quantity', models.CharField(default='', max_length=100)),
                ('half_exit_price', models.CharField(default='', max_length=100)),
                ('half_exit_time', models.DateTimeField(default=datetime.datetime(2022, 3, 15, 8, 51, 13, 726677, tzinfo=utc))),
                ('stoploss', models.CharField(default='', max_length=100)),
                ('target', models.CharField(default='', max_length=100)),
                ('sell_price', models.CharField(default='', max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 3, 15, 8, 51, 13, 726705, tzinfo=utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 3, 15, 8, 51, 13, 726712, tzinfo=utc))),
                ('status', models.CharField(default='', max_length=100)),
                ('p_n_l', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveTrade',
        ),
        migrations.AlterField(
            model_name='daywisesummery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 8, 51, 13, 726890, tzinfo=utc)),
        ),
    ]
