# Generated by Django 3.2.7 on 2022-03-20 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0012_auto_20220320_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tradebook',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tradebook',
            name='start_date',
        ),
        migrations.AddField(
            model_name='position',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 5, 20, 52, 38575, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='position',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 5, 20, 52, 38562, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tradebook',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 5, 20, 52, 38318, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tradebook',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 5, 20, 52, 38297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daywisesummery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 5, 20, 52, 38761, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 5, 20, 52, 38569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 5, 20, 52, 38311, tzinfo=utc)),
        ),
    ]
