# Generated by Django 3.2.7 on 2022-03-22 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0013_auto_20220320_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daywisesummery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 7, 19, 57, 214376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 7, 19, 57, 214187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 7, 19, 57, 214181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 7, 19, 57, 214173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 7, 19, 57, 213926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 7, 19, 57, 213919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 7, 19, 57, 213905, tzinfo=utc)),
        ),
    ]
