# Generated by Django 3.2.7 on 2022-03-23 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0015_auto_20220322_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoplossManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=100)),
                ('order_type', models.CharField(default='', max_length=100)),
                ('current_stoploss', models.CharField(default='', max_length=100)),
                ('target', models.CharField(default='', max_length=100)),
                ('target_done', models.BooleanField(default=False)),
                ('trail_list', models.TextField(default='')),
                ('trail_dict', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='daywisesummery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 7, 43, 9, 353640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 7, 43, 9, 353440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 7, 43, 9, 353434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 7, 43, 9, 353426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 7, 43, 9, 353156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 7, 43, 9, 353149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 7, 43, 9, 353135, tzinfo=utc)),
        ),
    ]
