# Generated by Django 3.2.7 on 2022-07-31 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0016_auto_20220323_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirydate',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 31, 5, 6, 6, 458872, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='daywisesummery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 6, 6, 459632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 6, 6, 459426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 6, 6, 459419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 6, 6, 459411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 6, 6, 459146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 6, 6, 459138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 6, 6, 459128, tzinfo=utc)),
        ),
    ]
