# Generated by Django 3.2.7 on 2022-07-31 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0017_auto_20220731_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirydate',
            name='front_value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expirydate',
            name='input_value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daywisesummery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 21, 348451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expirydate',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 31, 5, 15, 21, 347747, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='expirydate',
            name='expiry_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 21, 348263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 21, 348257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 21, 348250, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 21, 348005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 21, 347998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 21, 347989, tzinfo=utc)),
        ),
    ]
