# Generated by Django 3.2.7 on 2022-10-23 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OptionApp', '0018_auto_20220731_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daywisesummery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 48, 31, 441475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expirydate',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 23, 8, 48, 31, 440477, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 48, 31, 440944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 48, 31, 440937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 48, 31, 440930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 48, 31, 440685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='half_exit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 48, 31, 440678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 48, 31, 440669, tzinfo=utc)),
        ),
    ]
